using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using HarmonyLib;
using KSP.Localization;
using UnityEngine;

namespace SunkWorks.Submarine
{
    /// <summary>
    /// Describes a supercavity generated by a <see cref="WBISupercavitator"/> for the
    /// current physics tick.
    /// </summary>
    internal struct Supercavity
    {
        internal WBISupercavitator source;
        internal Vector3 origin;
        internal Vector3 axis;
        internal float length;
        internal float cavitatorRadius;
        internal float tipRadius;
        internal float maximumRadius;
        internal float expansionFraction;
        internal float straightLength;
        internal float strength;
        internal float residualDrag;

        internal float NoseLength
        {
            get
            {
                return Mathf.Clamp(length * expansionFraction, 0.01f,
                    Mathf.Max(0.01f, length - 0.01f));
            }
        }

        internal float TaperStartDistance
        {
            get
            {
                return Mathf.Clamp(NoseLength + straightLength, NoseLength,
                    Mathf.Max(NoseLength, length - 0.01f));
            }
        }

        internal float RadiusAt(float axialDistance)
        {
            axialDistance = Mathf.Clamp(axialDistance, 0f, length);
            float noseLength = NoseLength;

            if (axialDistance <= noseLength)
            {
                // A quarter ellipse creates a rounded, slightly elongated hemisphere
                // from the cavitator disk to the constant-radius cavity body.
                float expansionProgress = axialDistance / noseLength;
                float ellipseTerm = 1f - expansionProgress;
                float expansion = Mathf.Sqrt(Mathf.Max(0f,
                    1f - ellipseTerm * ellipseTerm));
                return Mathf.Lerp(tipRadius, maximumRadius, expansion);
            }

            float taperStart = TaperStartDistance;
            if (axialDistance <= taperStart)
                return maximumRadius;

            float collapse = Mathf.SmoothStep(0f, 1f,
                Mathf.InverseLerp(taperStart, length, axialDistance));
            return Mathf.Lerp(maximumRadius, 0f, collapse);
        }
    }

    /// <summary>
    /// Generates a tapered supercavity behind a submerged part. The model transform's
    /// local +Z axis is the cavitator's forward/nose direction.
    /// </summary>
    /// <example>
    /// <code>
    /// MODULE
    /// {
    ///     name = WBISupercavitator
    ///     cavityTransformName = cavitatorTransform
    ///     minimumCavitySpeed = 20
    ///     fullCavitySpeed = 40
    ///     cavitatorRadius = 0.25
    ///     maximumCavityRadius = 2.5
    ///     cavityLengthRadiusMultiplier = 10
    ///     cavityStraightRadiusMultiplier = 2
    ///     residualWaterDrag = 0.05
    /// }
    /// </code>
    /// </example>
    [KSPModule("Supercavitator")]
    public class WBISupercavitator : PartModule
    {
        const string kGroupName = "Supercavitation";

        /// <summary>
        /// Enables cavity generation. Resource requirements can be added later without
        /// changing the vessel-level geometry or drag patch.
        /// </summary>
        [KSPField(guiActive = true, guiActiveEditor = true,
            guiName = "#LOC_SUNKWORKS_supercavitationEnabled", isPersistant = true,
            groupName = kGroupName, groupDisplayName = "#LOC_SUNKWORKS_supercavitationGroup")]
        [UI_Toggle(enabledText = "#LOC_SUNKWORKS_on", disabledText = "#LOC_SUNKWORKS_off")]
        public bool cavityEnabled = true;

        /// <summary>
        /// Model transform at the cavitator. Its local +Z axis points toward the nose.
        /// The part transform is used when this is blank or cannot be found.
        /// </summary>
        [KSPField]
        public string cavityTransformName = string.Empty;

        /// <summary>Speed in m/s at which cavity formation begins.</summary>
        [KSPField]
        public float minimumCavitySpeed = 20f;

        /// <summary>Speed in m/s at which the cavity reaches full strength and size.</summary>
        [KSPField]
        public float fullCavitySpeed = 40f;

        /// <summary>Full cavity length measured in maximum cavity radii.</summary>
        [KSPField]
        public float cavityLengthRadiusMultiplier = 10f;

        /// <summary>Cavity radius at the cavitator in metres.</summary>
        [KSPField]
        public float cavitatorRadius = 0.25f;

        /// <summary>
        /// Radius of the cavity at its exact origin. Zero places the rounded nose tip
        /// directly at the cavitator transform.
        /// </summary>
        [KSPField]
        public float cavityTipRadius = 0f;

        /// <summary>Maximum full-strength cavity radius in metres.</summary>
        [KSPField(guiActiveEditor = true, isPersistant = true,
            guiName = "#LOC_SUNKWORKS_maximumCavityRadius",
            groupName = kGroupName,
            groupDisplayName = "#LOC_SUNKWORKS_supercavitationGroup")]
        [UI_FloatRange(minValue = 0.25f, maxValue = 5f, stepIncrement = 0.25f)]
        public float maximumCavityRadius = 2.5f;

        /// <summary>Fraction of cavity length used to expand to maximum radius.</summary>
        [KSPField]
        public float cavityExpansionFraction = 0.2f;

        /// <summary>
        /// Length of the constant-radius cavity body, measured in maximum cavity radii.
        /// </summary>
        [KSPField]
        public float cavityStraightRadiusMultiplier = 2f;

        /// <summary>
        /// How strongly the cavity axis follows water-relative velocity instead of the
        /// cavitator transform. Zero follows the transform; one follows velocity.
        /// </summary>
        [KSPField]
        public float velocityAlignment = 0.75f;

        /// <summary>Angle of attack in degrees below which alignment has full strength.</summary>
        [KSPField]
        public float fullStrengthAngle = 5f;

        /// <summary>Angle of attack in degrees at which the cavity collapses.</summary>
        [KSPField]
        public float collapseAngle = 20f;

        /// <summary>Submerged fraction needed for full cavity strength.</summary>
        [KSPField]
        public float fullStrengthSubmergedPortion = 0.5f;

        /// <summary>
        /// Fraction of stock water drag retained by a completely cavity-covered part.
        /// The cavitator itself is never protected by its own cavity.
        /// </summary>
        [KSPField]
        public float residualWaterDrag = 0.05f;

        /// <summary>
        /// Fraction of each INPUT_RESOURCE rate consumed while the cavity is growing.
        /// </summary>
        [KSPField]
        public float formationGasRate = 1f;

        /// <summary>
        /// Fraction of each INPUT_RESOURCE rate consumed while the cavity is stable.
        /// </summary>
        [KSPField]
        public float sustainGasRate = 0.15f;

        /// <summary>
        /// Fractional sustain-rate increase for each atmosphere of ambient pressure.
        /// </summary>
        [KSPField]
        public float depthGasMultiplier = 0.02f;

        /// <summary>
        /// Maximum sustain-rate multiplier while pitch, yaw, or roll input is applied.
        /// </summary>
        [KSPField]
        public float maneuverGasMultiplier = 2f;

        /// <summary>Enables rate-limited cavity diagnostics in KSP.log.</summary>
        [KSPField]
        public bool debugMode;

        /// <summary>Logs the final drag multiplier for every covered part.</summary>
        [KSPField]
        public bool verboseDebug;

        /// <summary>Minimum seconds between diagnostic snapshots.</summary>
        [KSPField]
        public float debugLogInterval = 1f;

        /// <summary>Current cavity state shown in the part action window.</summary>
        [KSPField(guiActive = true, guiName = "#LOC_SUNKWORKS_supercavitationStatus",
            groupName = kGroupName, groupDisplayName = "#LOC_SUNKWORKS_supercavitationGroup")]
        public string cavityStatus = string.Empty;

        Transform cavityTransform;
        readonly List<ResourceRatio> inputResources = new List<ResourceRatio>();
        bool transformWarningLogged;
        bool hasCurrentSupercavity;
        Supercavity currentSupercavity;

        internal float DiagnosticSpeed { get; private set; }
        internal float DiagnosticAngleOfAttack { get; private set; }
        internal float DiagnosticStrength { get; private set; }
        internal int DiagnosticInputResourceCount { get; private set; }
        internal double DiagnosticResourceRate { get; private set; }
        internal string DiagnosticResourceMode { get; private set; }

        /// <summary>
        /// Current normalized cavity size from zero (no cavity) to one (full cavity).
        /// </summary>
        public float CavityScale { get; private set; }

        internal float FullCavityLength
        {
            get
            {
                return maximumCavityRadius * cavityLengthRadiusMultiplier;
            }
        }

        internal Transform CavityTransform
        {
            get
            {
                resolveCavityTransform();
                return cavityTransform;
            }
        }

        internal bool TryGetCurrentSupercavity(out Supercavity cavity)
        {
            cavity = currentSupercavity;
            return hasCurrentSupercavity;
        }

        internal bool TryGetEditorPreviewSupercavity(out Supercavity cavity)
        {
            cavity = default(Supercavity);
            if (!cavityEnabled || !HighLogic.LoadedSceneIsEditor || part == null)
                return false;

            resolveCavityTransform();
            cavity = new Supercavity
            {
                source = this,
                origin = cavityTransform.position,
                axis = -cavityTransform.forward.normalized,
                length = FullCavityLength,
                cavitatorRadius = cavitatorRadius,
                tipRadius = cavityTipRadius,
                maximumRadius = maximumCavityRadius,
                expansionFraction = cavityExpansionFraction,
                straightLength = maximumCavityRadius * cavityStraightRadiusMultiplier,
                strength = 1f,
                residualDrag = residualWaterDrag
            };
            return true;
        }

        /// <summary>Loads INPUT_RESOURCE definitions from the module configuration.</summary>
        public override void OnLoad(ConfigNode node)
        {
            base.OnLoad(node);

            ConfigNode[] resourceNodes = node.GetNodes("INPUT_RESOURCE");
            if (resourceNodes.Length == 0)
                return;

            inputResources.Clear();
            for (int index = 0; index < resourceNodes.Length; index++)
            {
                try
                {
                    ResourceRatio resource = new ResourceRatio
                    {
                        FlowMode = ResourceFlowMode.NULL
                    };
                    resource.Load(resourceNodes[index]);
                    if (!string.IsNullOrEmpty(resource.ResourceName) && resource.Ratio > 0.0)
                        inputResources.Add(resource);
                }
                catch (Exception ex)
                {
                    Debug.LogError("[SunkWorks] WBISupercavitator could not load " +
                        "INPUT_RESOURCE: " + ex);
                }
            }
        }

        /// <summary>Toggles the cavitator through an action group.</summary>
        [KSPAction("#LOC_SUNKWORKS_toggleSupercavitation")]
        public void ToggleCavityAction(KSPActionParam param)
        {
            cavityEnabled = !cavityEnabled;
        }

        /// <summary>Initializes and clamps the configurable cavity parameters.</summary>
        public override void OnStart(StartState state)
        {
            base.OnStart(state);

            // Craft and save MODULE nodes contain persistent KSPFields, but KSP does
            // not copy custom child nodes such as INPUT_RESOURCE into the flight
            // instance. Restore the recipe parsed by the matching prefab module.
            ensureInputResourcesLoaded();

            minimumCavitySpeed = Mathf.Max(0f, minimumCavitySpeed);
            fullCavitySpeed = Mathf.Max(minimumCavitySpeed + 0.01f, fullCavitySpeed);
            cavitatorRadius = Mathf.Max(0.001f, cavitatorRadius);
            maximumCavityRadius = Mathf.Clamp(maximumCavityRadius, cavitatorRadius, 5f);
            cavityLengthRadiusMultiplier = Mathf.Max(0.01f, cavityLengthRadiusMultiplier);
            cavityTipRadius = Mathf.Clamp(cavityTipRadius, 0f, maximumCavityRadius);
            cavityExpansionFraction = Mathf.Clamp(cavityExpansionFraction, 0.01f, 0.99f);
            cavityStraightRadiusMultiplier = Mathf.Max(0f, cavityStraightRadiusMultiplier);
            velocityAlignment = Mathf.Clamp01(velocityAlignment);
            fullStrengthAngle = Mathf.Clamp(fullStrengthAngle, 0f, 179f);
            collapseAngle = Mathf.Clamp(collapseAngle, fullStrengthAngle + 0.01f, 180f);
            fullStrengthSubmergedPortion = Mathf.Clamp(fullStrengthSubmergedPortion, 0.01f, 1f);
            residualWaterDrag = Mathf.Clamp01(residualWaterDrag);
            formationGasRate = Mathf.Max(0f, formationGasRate);
            sustainGasRate = Mathf.Max(0f, sustainGasRate);
            depthGasMultiplier = Mathf.Max(0f, depthGasMultiplier);
            maneuverGasMultiplier = Mathf.Max(1f, maneuverGasMultiplier);
            debugLogInterval = Mathf.Max(0.1f, debugLogInterval);

            resolveCavityTransform();
            setCavityScale(0f);
            cavityStatus = cavityEnabled
                ? Localizer.Format("#LOC_SUNKWORKS_supercavitationWaiting")
                : Localizer.Format("#LOC_SUNKWORKS_supercavitationDisabled");

            if (debugMode)
            {
                Debug.Log("[WBISupercavitator] Loaded " + inputResources.Count +
                    " INPUT_RESOURCE definition(s) on '" + part.partInfo.title + "'.");
            }
        }

        /// <summary>Gets the editor description.</summary>
        public override string GetInfo()
        {
            ensureInputResourcesLoaded();

            string cavityInfo = Localizer.Format("#LOC_SUNKWORKS_supercavitationInfo",
                minimumCavitySpeed.ToString("F0"),
                FullCavityLength.ToString("F1"));

            if (inputResources.Count == 0)
                return cavityInfo;

            return cavityInfo + Localizer.Format("#LOC_SUNKWORKS_supercavitationResourceInfo",
                formatResourceRates(formationGasRate),
                formatResourceRates(sustainGasRate));
        }

        /// <summary>
        /// Consumes the resources needed to grow or sustain the requested cavity.
        /// </summary>
        protected virtual bool CanMaintainCavity(float requestedStrength)
        {
            ensureInputResourcesLoaded();
            DiagnosticInputResourceCount = inputResources.Count;
            DiagnosticResourceRate = 0.0;
            DiagnosticResourceMode = "none";

            if (inputResources.Count == 0)
                return true;

            bool isForming = CavityScale + 0.001f < requestedStrength;
            double rateMultiplier = isForming
                ? formationGasRate
                : calculateSustainRateMultiplier();
            DiagnosticResourceMode = isForming ? "formation" : "sustain";
            double elapsedTime = TimeWarp.fixedDeltaTime;
            if (rateMultiplier <= 0.0 || elapsedTime <= 0.0)
                return true;

            // Check every input first so a failed multi-resource recipe does not consume
            // the resources that happened to be checked before the missing one.
            for (int index = 0; index < inputResources.Count; index++)
            {
                ResourceRatio resource = inputResources[index];
                PartResourceDefinition definition =
                    PartResourceLibrary.Instance.GetDefinition(resource.ResourceName);
                if (definition == null)
                    return false;

                ResourceFlowMode flowMode = getFlowMode(resource, definition);
                double demand = resource.Ratio * rateMultiplier * elapsedTime;
                DiagnosticResourceRate += resource.Ratio * rateMultiplier;
                double available;
                double capacity;
                part.GetConnectedResourceTotals(definition.id, flowMode,
                    out available, out capacity, true);
                if (available + 1e-8 < demand)
                    return false;
            }

            for (int index = 0; index < inputResources.Count; index++)
            {
                ResourceRatio resource = inputResources[index];
                PartResourceDefinition definition =
                    PartResourceLibrary.Instance.GetDefinition(resource.ResourceName);
                ResourceFlowMode flowMode = getFlowMode(resource, definition);
                double demand = resource.Ratio * rateMultiplier * elapsedTime;
                part.RequestResource(definition.id, demand, flowMode);
            }
            return true;
        }

        internal bool TryGetSupercavity(out Supercavity cavity)
        {
            cavity = default(Supercavity);
            hasCurrentSupercavity = false;
            DiagnosticSpeed = 0f;
            DiagnosticAngleOfAttack = 0f;
            DiagnosticStrength = 0f;

            if (!cavityEnabled)
            {
                setCavityScale(0f);
                cavityStatus = Localizer.Format("#LOC_SUNKWORKS_supercavitationDisabled");
                return false;
            }
            if (part == null || vessel == null || part.rb == null || vessel.packed ||
                vessel.mainBody == null || !vessel.mainBody.ocean || !part.WaterContact ||
                part.submergedPortion <= 0.0)
            {
                setCavityScale(0f);
                cavityStatus = Localizer.Format("#LOC_SUNKWORKS_supercavitationDry");
                return false;
            }
            Vector3 waterRelativeVelocity = part.rb.velocity + Krakensbane.GetFrameVelocityV3f();
            float speed = waterRelativeVelocity.magnitude;
            DiagnosticSpeed = speed;
            if (speed <= minimumCavitySpeed)
            {
                setCavityScale(0f);
                cavityStatus = Localizer.Format("#LOC_SUNKWORKS_supercavitationTooSlow",
                    speed.ToString("F1"));
                return false;
            }

            resolveCavityTransform();
            Vector3 velocityDirection = waterRelativeVelocity / speed;
            Vector3 cavitatorForward = cavityTransform.forward.normalized;
            float angleOfAttack = Vector3.Angle(cavitatorForward, velocityDirection);
            DiagnosticAngleOfAttack = angleOfAttack;
            float angleStrength = 1f - Mathf.SmoothStep(0f, 1f,
                Mathf.InverseLerp(fullStrengthAngle, collapseAngle, angleOfAttack));
            if (angleStrength <= 0f)
            {
                setCavityScale(0f);
                cavityStatus = Localizer.Format("#LOC_SUNKWORKS_supercavitationMisaligned",
                    angleOfAttack.ToString("F1"));
                return false;
            }

            float speedStrength = Mathf.SmoothStep(0f, 1f,
                Mathf.InverseLerp(minimumCavitySpeed, fullCavitySpeed, speed));
            float submergedStrength = Mathf.Clamp01(
                (float)part.submergedPortion / fullStrengthSubmergedPortion);
            float strength = speedStrength * angleStrength * submergedStrength;
            DiagnosticStrength = strength;
            if (strength <= 0f)
            {
                setCavityScale(0f);
                return false;
            }

            if (!CanMaintainCavity(strength))
            {
                setCavityScale(0f);
                cavityStatus = Localizer.Format("#LOC_SUNKWORKS_supercavitationUnavailable");
                return false;
            }

            setCavityScale(strength);

            // Both vectors point aft. The blend lets the flow bend the cavity while the
            // cavitator transform still limits unrealistic sideways operation.
            Vector3 transformWakeAxis = -cavitatorForward;
            Vector3 flowWakeAxis = -velocityDirection;
            Vector3 wakeAxis = Vector3.Slerp(transformWakeAxis, flowWakeAxis,
                velocityAlignment).normalized;

            float currentMaximumRadius = Mathf.Lerp(
                cavitatorRadius, maximumCavityRadius, strength);
            cavity = new Supercavity
            {
                source = this,
                origin = cavityTransform.position,
                axis = wakeAxis,
                length = currentMaximumRadius * cavityLengthRadiusMultiplier,
                cavitatorRadius = cavitatorRadius,
                tipRadius = cavityTipRadius,
                maximumRadius = currentMaximumRadius,
                expansionFraction = cavityExpansionFraction,
                straightLength = currentMaximumRadius * cavityStraightRadiusMultiplier,
                strength = strength,
                residualDrag = residualWaterDrag
            };
            currentSupercavity = cavity;
            hasCurrentSupercavity = true;

            cavityStatus = Localizer.Format("#LOC_SUNKWORKS_supercavitationActive",
                (strength * 100f).ToString("F0"));
            return true;
        }

        void setCavityScale(float scale)
        {
            CavityScale = Mathf.Clamp01(scale);
        }

        double calculateSustainRateMultiplier()
        {
            double ambientAtmospheres = part != null
                ? Math.Max(0.0, part.staticPressureAtm)
                : 0.0;
            double depthMultiplier = 1.0 + ambientAtmospheres * depthGasMultiplier;

            float maneuverInput = 0f;
            if (vessel != null && vessel.ctrlState != null)
            {
                maneuverInput = Mathf.Clamp01(Mathf.Max(
                    Mathf.Abs(vessel.ctrlState.pitch),
                    Mathf.Max(Mathf.Abs(vessel.ctrlState.yaw),
                        Mathf.Abs(vessel.ctrlState.roll))));
            }
            double maneuverMultiplier = Mathf.Lerp(1f,
                maneuverGasMultiplier, maneuverInput);
            return sustainGasRate * depthMultiplier * maneuverMultiplier;
        }

        string formatResourceRates(float rateFraction)
        {
            StringBuilder builder = new StringBuilder();
            for (int index = 0; index < inputResources.Count; index++)
            {
                if (index > 0)
                    builder.Append(", ");

                ResourceRatio resource = inputResources[index];
                PartResourceDefinition definition =
                    PartResourceLibrary.Instance.GetDefinition(resource.ResourceName);
                string displayName = definition != null
                    ? definition.displayName
                    : resource.ResourceName;
                builder.Append(displayName);
                builder.Append(": ");
                builder.Append((resource.Ratio * rateFraction).ToString("0.#####"));
                builder.Append("/s");
            }
            return builder.ToString();
        }

        static ResourceFlowMode getFlowMode(ResourceRatio resource,
            PartResourceDefinition definition)
        {
            return resource.FlowMode != ResourceFlowMode.NULL
                ? resource.FlowMode
                : definition.resourceFlowMode;
        }

        void ensureInputResourcesLoaded()
        {
            if (inputResources.Count > 0 || part == null || part.partInfo == null ||
                part.partInfo.partPrefab == null)
                return;

            Part prefab = part.partInfo.partPrefab;
            WBISupercavitator prefabModule = null;

            // Module ordering is preserved from the prefab into craft and flight
            // instances. Prefer the same slot so parts may define more than one
            // supercavitator without sharing the wrong recipe.
            int moduleIndex = part.Modules.IndexOf(this);
            if (moduleIndex >= 0 && moduleIndex < prefab.Modules.Count)
                prefabModule = prefab.Modules[moduleIndex] as WBISupercavitator;

            if (prefabModule == null || ReferenceEquals(prefabModule, this))
                prefabModule = prefab.FindModuleImplementing<WBISupercavitator>();

            if (prefabModule == null || ReferenceEquals(prefabModule, this) ||
                prefabModule.inputResources.Count == 0)
                return;

            inputResources.AddRange(prefabModule.inputResources);
        }

        void resolveCavityTransform()
        {
            if (cavityTransform != null)
                return;

            if (!string.IsNullOrEmpty(cavityTransformName))
                cavityTransform = part.FindModelTransform(cavityTransformName);

            if (cavityTransform == null)
            {
                cavityTransform = part.partTransform;
                if (!string.IsNullOrEmpty(cavityTransformName) && !transformWarningLogged)
                {
                    transformWarningLogged = true;
                    Debug.LogWarning("[SunkWorks] WBISupercavitator on " + part.partInfo.title +
                        " could not find transform '" + cavityTransformName +
                        "'; using the part transform.");
                }
            }
        }
    }

    /// <summary>
    /// Calculates all supercavity coverage for one loaded vessel once per physics tick.
    /// </summary>
    public class WBISupercavitationController : VesselModule
    {
        sealed class ControllerReference
        {
            internal WBISupercavitationController controller;
        }

        static readonly ConditionalWeakTable<Vessel, ControllerReference> controllerRegistry =
            new ConditionalWeakTable<Vessel, ControllerReference>();

        struct DragApplication
        {
            internal float stockDrag;
            internal float appliedDrag;
        }

        readonly Dictionary<Part, float> dragMultipliers = new Dictionary<Part, float>();
        readonly Dictionary<Part, float> cavityCoverages = new Dictionary<Part, float>();
        readonly Dictionary<Part, DragApplication> currentDragApplications =
            new Dictionary<Part, DragApplication>();
        readonly Dictionary<Part, DragApplication> previousDragApplications =
            new Dictionary<Part, DragApplication>();
        readonly List<Supercavity> activeCavities = new List<Supercavity>();
        List<WBISupercavitator> cavitators = new List<WBISupercavitator>();
        int cachedPartCount = -1;
        float lastUpdateFixedTime = float.MinValue;
        double nextDiagnosticTime;

        /// <summary>
        /// Gets the registered supercavitation controller for a loaded vessel without
        /// repeatedly searching its VesselModules.
        /// </summary>
        public static bool TryGetController(Vessel targetVessel,
            out WBISupercavitationController controller)
        {
            controller = null;
            if (targetVessel == null)
                return false;

            ControllerReference reference;
            if (!controllerRegistry.TryGetValue(targetVessel, out reference) ||
                reference == null || reference.controller == null)
            {
                return false;
            }

            controller = reference.controller;
            return true;
        }

        protected override void OnAwake()
        {
            base.OnAwake();
            if (vessel == null)
                return;

            ControllerReference reference;
            if (controllerRegistry.TryGetValue(vessel, out reference))
            {
                reference.controller = this;
            }
            else
            {
                controllerRegistry.Add(vessel, new ControllerReference
                {
                    controller = this
                });
            }
        }

        void OnDestroy()
        {
            if (vessel == null)
                return;

            ControllerReference reference;
            if (controllerRegistry.TryGetValue(vessel, out reference) &&
                reference != null && reference.controller == this)
            {
                controllerRegistry.Remove(vessel);
            }
        }

        /// <summary>Limits this controller to loaded vessels in the flight scene.</summary>
        public override Activation GetActivation()
        {
            return Activation.FlightScene | Activation.LoadedVessels;
        }

        /// <summary>Returns whether this vessel is currently available for physics.</summary>
        public override bool ShouldBeActive()
        {
            return HighLogic.LoadedSceneIsFlight && vessel != null && vessel.loaded;
        }

        /// <summary>Returns the stock-water-drag multiplier for a vessel part.</summary>
        public float GetWaterDragMultiplier(Part vesselPart)
        {
            ensureCoverageCurrent();

            float multiplier;
            return vesselPart != null && dragMultipliers.TryGetValue(vesselPart, out multiplier)
                ? multiplier
                : 1f;
        }

        /// <summary>
        /// Returns the current normalized supercavity coverage of a vessel part.
        /// Zero is returned when the part is not covered or the vessel has no active
        /// supercavitator.
        /// </summary>
        public float GetSupercavityCoverage(Part vesselPart)
        {
            ensureCoverageCurrent();

            float coverage;
            return vesselPart != null && cavityCoverages.TryGetValue(vesselPart, out coverage)
                ? coverage
                : 0f;
        }

        internal void RecordWaterDragApplication(Part vesselPart, float stockDrag, float appliedDrag)
        {
            if (vesselPart == null)
                return;

            currentDragApplications[vesselPart] = new DragApplication
            {
                stockDrag = stockDrag,
                appliedDrag = appliedDrag
            };
        }

        void ensureCoverageCurrent()
        {
            if (lastUpdateFixedTime == Time.fixedTime)
                return;

            lastUpdateFixedTime = Time.fixedTime;
            previousDragApplications.Clear();
            foreach (KeyValuePair<Part, DragApplication> entry in currentDragApplications)
                previousDragApplications[entry.Key] = entry.Value;
            currentDragApplications.Clear();
            dragMultipliers.Clear();
            cavityCoverages.Clear();
            activeCavities.Clear();

            if (vessel == null || !vessel.loaded || vessel.packed)
                return;

            if (cachedPartCount != vessel.parts.Count)
            {
                cachedPartCount = vessel.parts.Count;
                cavitators = vessel.FindPartModulesImplementing<WBISupercavitator>();
            }

            for (int index = 0; index < cavitators.Count; index++)
            {
                Supercavity cavity;
                if (cavitators[index] != null && cavitators[index].TryGetSupercavity(out cavity))
                    activeCavities.Add(cavity);
            }

            for (int cavityIndex = 0; cavityIndex < activeCavities.Count; cavityIndex++)
                applyCavity(activeCavities[cavityIndex]);

            logDiagnostics();
        }

        void logDiagnostics()
        {
            bool diagnosticsEnabled = false;
            bool verbose = false;
            float interval = float.MaxValue;

            for (int index = 0; index < cavitators.Count; index++)
            {
                WBISupercavitator cavitator = cavitators[index];
                if (cavitator == null || !cavitator.debugMode)
                    continue;

                diagnosticsEnabled = true;
                verbose |= cavitator.verboseDebug;
                interval = Mathf.Min(interval, cavitator.debugLogInterval);
            }

            if (!diagnosticsEnabled)
                return;

            double currentTime = Planetarium.GetUniversalTime();
            if (currentTime < nextDiagnosticTime)
                return;
            nextDiagnosticTime = currentTime + Math.Max(0.1f, interval);

            float minimumMultiplier = 1f;
            foreach (float multiplier in dragMultipliers.Values)
                minimumMultiplier = Mathf.Min(minimumMultiplier, multiplier);

            float summedStockRigidbodyDrag = 0f;
            float summedAppliedRigidbodyDrag = 0f;
            foreach (DragApplication application in previousDragApplications.Values)
            {
                summedStockRigidbodyDrag += application.stockDrag;
                summedAppliedRigidbodyDrag += application.appliedDrag;
            }

            int vesselWaterContactParts = 0;
            int vesselSubmergedParts = 0;
            int vesselShieldedParts = 0;
            for (int index = 0; index < vessel.parts.Count; index++)
            {
                Part vesselPart = vessel.parts[index];
                if (vesselPart == null)
                    continue;

                if (vesselPart.WaterContact)
                    vesselWaterContactParts++;
                if (vesselPart.submergedPortion > 0.0)
                    vesselSubmergedParts++;
                if (vesselPart.ShieldedFromAirstream)
                    vesselShieldedParts++;
            }

            int coveredSubmergedParts = 0;
            int coveredZeroSubmergedParts = 0;
            int coveredShieldedParts = 0;
            int coveredPhysicslessParts = 0;
            foreach (Part coveredPart in dragMultipliers.Keys)
            {
                if (coveredPart.submergedPortion > 0.0)
                    coveredSubmergedParts++;
                else
                    coveredZeroSubmergedParts++;
                if (coveredPart.ShieldedFromAirstream)
                    coveredShieldedParts++;
                if (coveredPart.physicalSignificance == Part.PhysicalSignificance.NONE)
                    coveredPhysicslessParts++;
            }

            List<ModuleEngines> engines = vessel.FindPartModulesImplementing<ModuleEngines>();
            int ignitedEngines = 0;
            int producingEngines = 0;
            float totalThrust = 0f;
            float configuredMaximumThrust = 0f;
            for (int index = 0; index < engines.Count; index++)
            {
                ModuleEngines engine = engines[index];
                if (engine == null)
                    continue;

                if (engine.EngineIgnited)
                    ignitedEngines++;
                if (engine.finalThrust > 0f)
                    producingEngines++;
                totalThrust += engine.finalThrust;
                configuredMaximumThrust += engine.maxThrust * engine.thrustPercentage * 0.01f;
            }

            Debug.Log("[WBISupercavitator] vessel='" + vessel.GetDisplayName() +
                "' cavitators=" + cavitators.Count +
                " activeCavities=" + activeCavities.Count +
                " coveredParts=" + dragMultipliers.Count +
                " coveredSubmerged=" + coveredSubmergedParts +
                " coveredZeroSubmerged=" + coveredZeroSubmergedParts +
                " coveredShielded=" + coveredShieldedParts +
                " coveredPhysicsless=" + coveredPhysicslessParts +
                " vesselWaterContact=" + vesselWaterContactParts + "/" + vessel.parts.Count +
                " vesselSubmerged=" + vesselSubmergedParts + "/" + vessel.parts.Count +
                " vesselShielded=" + vesselShieldedParts +
                " dragPatchedParts=" + previousDragApplications.Count +
                " summedStockRbDrag=" + summedStockRigidbodyDrag.ToString("F3") +
                " summedAppliedRbDrag=" + summedAppliedRigidbodyDrag.ToString("F3") +
                " minimumDragMultiplier=" + minimumMultiplier.ToString("F3"));

            Debug.Log("[WBISupercavitator] propulsion engines=" + engines.Count +
                " ignited=" + ignitedEngines +
                " producing=" + producingEngines +
                " thrust=" + totalThrust.ToString("F2") + "kN" +
                " configuredMaximum=" + configuredMaximumThrust.ToString("F2") + "kN");

            for (int index = 0; index < cavitators.Count; index++)
            {
                WBISupercavitator cavitator = cavitators[index];
                if (cavitator == null || !cavitator.debugMode)
                    continue;

                string partTitle = cavitator.part != null && cavitator.part.partInfo != null
                    ? cavitator.part.partInfo.title
                    : "unknown";
                Debug.Log("[WBISupercavitator] cavitator='" + partTitle +
                    "' enabled=" + cavitator.cavityEnabled +
                    " status='" + cavitator.cavityStatus +
                    "' speed=" + cavitator.DiagnosticSpeed.ToString("F2") + "m/s" +
                    " aoa=" + cavitator.DiagnosticAngleOfAttack.ToString("F2") + "deg" +
                    " strength=" + (cavitator.DiagnosticStrength * 100f).ToString("F1") + "%" +
                    " inputResources=" + cavitator.DiagnosticInputResourceCount +
                    " gasMode=" + cavitator.DiagnosticResourceMode +
                    " gasRate=" + cavitator.DiagnosticResourceRate.ToString("F5") + "/s");
            }

            if (!verbose)
                return;

            foreach (KeyValuePair<Part, float> entry in dragMultipliers)
            {
                string partTitle = entry.Key.partInfo != null
                    ? entry.Key.partInfo.title
                    : entry.Key.partName;
                DragApplication dragApplication;
                bool dragWasApplied = previousDragApplications.TryGetValue(
                    entry.Key, out dragApplication);
                Debug.Log("[WBISupercavitator] coveredPart='" + partTitle +
                    "' flightID=" + entry.Key.flightID +
                    " submerged=" + entry.Key.submergedPortion.ToString("F3") +
                    " waterContact=" + entry.Key.WaterContact +
                    " shielded=" + entry.Key.ShieldedFromAirstream +
                    " physicalSignificance=" + entry.Key.physicalSignificance +
                    " dragMultiplier=" + entry.Value.ToString("F3") +
                    " dragApplied=" + dragWasApplied +
                    (dragWasApplied
                        ? " stockRbDrag=" + dragApplication.stockDrag.ToString("F3") +
                          " appliedRbDrag=" + dragApplication.appliedDrag.ToString("F3")
                        : string.Empty));
            }


            for (int index = 0; index < engines.Count; index++)
            {
                ModuleEngines engine = engines[index];
                if (engine == null)
                    continue;

                string partTitle = engine.part != null && engine.part.partInfo != null
                    ? engine.part.partInfo.title
                    : "unknown";
                Debug.Log("[WBISupercavitator] engine='" + partTitle +
                    "' engineID='" + engine.engineID +
                    "' ignited=" + engine.EngineIgnited +
                    " flameout=" + engine.flameout +
                    " throttle=" + (engine.currentThrottle * 100f).ToString("F1") + "%" +
                    " thrust=" + engine.finalThrust.ToString("F2") + "kN" +
                    " configuredMaximum=" +
                    (engine.maxThrust * engine.thrustPercentage * 0.01f).ToString("F2") + "kN");
            }
        }

        void applyCavity(Supercavity cavity)
        {
            for (int partIndex = 0; partIndex < vessel.parts.Count; partIndex++)
            {
                Part candidate = vessel.parts[partIndex];
                if (candidate == null || candidate == cavity.source.part)
                    continue;

                float coverage = calculateCoverage(candidate, cavity) * cavity.strength;
                if (coverage <= 0f)
                    continue;

                float currentCoverage;
                if (!cavityCoverages.TryGetValue(candidate, out currentCoverage) ||
                    coverage > currentCoverage)
                {
                    cavityCoverages[candidate] = coverage;
                }

                float multiplier = Mathf.Lerp(1f, cavity.residualDrag, coverage);
                float currentMultiplier;
                if (!dragMultipliers.TryGetValue(candidate, out currentMultiplier) ||
                    multiplier < currentMultiplier)
                {
                    dragMultipliers[candidate] = multiplier;
                }
            }
        }

        static float calculateCoverage(Part candidate, Supercavity cavity)
        {
            Vector3 localCenter = Vector3.zero;
            Vector3 halfSize = Vector3.zero;
            bool hasDragCubeBounds = candidate.DragCubes != null && !candidate.DragCubes.None;
            if (hasDragCubeBounds)
            {
                localCenter = candidate.DragCubes.WeightedCenter;
                halfSize = candidate.DragCubes.WeightedSize * 0.5f;
                hasDragCubeBounds = halfSize.sqrMagnitude > 1e-6f;
            }

            Transform partTransform = candidate.partTransform;
            if (!hasDragCubeBounds)
            {
                return isInsideCavity(partTransform.position, cavity) ? 1f : 0f;
            }

            int pointsInside = isInsideCavity(
                partTransform.TransformPoint(localCenter), cavity) ? 1 : 0;

            for (int x = -1; x <= 1; x += 2)
            {
                for (int y = -1; y <= 1; y += 2)
                {
                    for (int z = -1; z <= 1; z += 2)
                    {
                        Vector3 localPoint = localCenter + new Vector3(
                            halfSize.x * x,
                            halfSize.y * y,
                            halfSize.z * z);
                        if (isInsideCavity(partTransform.TransformPoint(localPoint), cavity))
                            pointsInside++;
                    }
                }
            }

            return pointsInside / 9f;
        }

        static bool isInsideCavity(Vector3 point, Supercavity cavity)
        {
            Vector3 offset = point - cavity.origin;
            float axialDistance = Vector3.Dot(offset, cavity.axis);
            if (axialDistance <= 0f || axialDistance >= cavity.length)
                return false;

            Vector3 radialOffset = offset - cavity.axis * axialDistance;
            float radius = cavity.RadiusAt(axialDistance);
            return radialOffset.sqrMagnitude <= radius * radius;
        }
    }

    /// <summary>
    /// Reduces the stock PartBuoyancy translational damping after it has calculated
    /// water drag. Cavity geometry is calculated once per vessel per physics tick.
    /// </summary>
    [HarmonyPatch(typeof(PartBuoyancy), "FixedUpdate")]
    internal static class WBISupercavitationDragPatch
    {
        static void Postfix(Part ___part)
        {
            if (___part == null || ___part.rb == null || ___part.vessel == null ||
                ___part.submergedPortion <= 0.0)
                return;

            WBISupercavitationController controller;
            if (!WBISupercavitationController.TryGetController(
                ___part.vessel, out controller))
                return;

            float multiplier = controller.GetWaterDragMultiplier(___part);
            if (multiplier >= 1f)
                return;

            float stockDrag = ___part.rb.drag;
            ___part.rb.drag *= multiplier;
            if (___part.servoRb != null)
                ___part.servoRb.drag *= multiplier;
            controller.RecordWaterDragApplication(___part, stockDrag, ___part.rb.drag);
        }
    }
}
